site_name: Toy Adapting Instructions
site_description: Neil Squire's Makers Making Change
site_url: https://makersmakingchange.github.io/Switch_Adapted_Toys/
use_directory_urls: true 

nav:
  - Latest Updates: updates.md
  - Start Here: index.md
  - Toy Instructions: toy-instructions.md
  - Resources for Toy Adapting: toy-resources.md

theme:
  name: material
  logo: docs\images\Interact_black.png 
  custom_dir: overrides
  font:
    text: Open Sans
    Code: Roboto Mono
  Logo: images
  icon:
    admonition:
      type: material/alert-octagon
  features:
    - navigation.footer # this addes previous and next buttons at the bottom
    - navigation.instant  # Optional: makes page loads feel faster
  palette:
    - scheme: default
      primary: custom # This tells MkDocs we are overriding via CSS
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - with-pdf
  - include-markdown

extra_css:
  - styles/extra.css

extra_javascript:
  - extra.js
  - js/toy-data.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences # Highly recommended for better code/block handling
  - md_in_html
  - tables
  - attr_list
  - toc:
      toc_depth: 3